image: ruby:2.3

cache:
  paths: 
    - vendor/

before_script:
  - bundle install --path vendor

build:
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d web
  artifacts:
    paths:
      - web