image: ruby:2.5.1

cache:
  paths: 
    - vendor/

before_script:
  - bundle install --path vendor
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build:
  only:
    - master
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d web
  artifacts:
    paths:
      - web

deploy:
  stage: build
  script:
    - apt-get update && apt-get install rsync 
    - rsync -r web/ patjennings@86.229.179.47:/var/www/thomasguesnon.net
  only:
    - master

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  USERNAME: "patjennet"
  PASSWORD: "quRYNMFJu"
  HOST: "86.229.179.47"