image: ruby:2.5.1

cache:
  paths: 
    - vendor/

before_script:
  - bundle install --path vendor
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY"
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

build:
  only:
    - master
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d public
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - public

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - scp -rp ./public/* patjennings@81.53.198.226:/var/www/thomasguesnon.net
  only:
    - master

# this prevents some problem @ converting sass in Jekyll (US ASCII error when converting)
variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  USERNAME: "patjennet"
  PASSWORD: "quRYNMFJu"
  HOST: "81.53.198.226"

# phase build : création d'un artifact public/, que l'on utilise dans le job deploy. Cet artifact public/ n'est utilisable que dans le contexte du build. On y accède, dans deploy, grâce à dependencies: - build
