image: ruby:2.5.1

cache:
  paths: 
    - vendor/

before_script:
  - bundle install --path vendor

build:
  only:
    - master
  stage: build
  script:
    - JEKYLL_ENV=production bundle exec jekyll build -d web
  artifacts:
    paths:
      - web

deploy:
  stage: build
  script:
    - apt-get update && apt-get install sshpass
    - sshpass -p "ctVic2011" scp -r web patjennings@86.229.179.47:/var/www/thomasguesnon.net/ci-test
  only:
    - master

variables:
  LC_ALL: "C.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  USERNAME: "patjennet"
  PASSWORD: "quRYNMFJu"
  HOST: "86.229.179.47"